/**
 * Client-side PDF export for financial calculator results.
 * Uses jsPDF to generate a branded PDF with the calculator's key results.
 * No charts — just clean formatted numbers and breakdowns.
 */

export interface PdfSection {
  /** Section heading (e.g. "Summary", "Monthly Breakdown") */
  title: string;
  /** Key-value pairs to display */
  rows: { label: string; value: string }[];
}

export interface PdfExportData {
  toolName: string;
  sections: PdfSection[];
}

export async function exportToPdf(data: PdfExportData): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Header accent bar
  doc.setFillColor(37, 99, 235); // primary-500
  doc.rect(0, 0, pageWidth, 4, 'F');

  // Logo text
  y = 18;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(10, 37, 64); // navy
  doc.text('Calc', margin, y);
  const calcWidth = doc.getTextWidth('Calc');
  doc.setTextColor(37, 99, 235); // primary
  doc.text('Run', margin + calcWidth, y);
  const runWidth = doc.getTextWidth('Run');

  // Date on the right
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184); // slate-400
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  doc.text(dateStr, pageWidth - margin, y, { align: 'right' });

  // Tool name
  y = 30;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(10, 37, 64);
  doc.text(data.toolName, margin, y);

  // Divider
  y += 4;
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Sections
  for (const section of data.sections) {
    // Check if we need a new page
    const sectionHeight = 10 + section.rows.length * 7;
    if (y + sectionHeight > 270) {
      doc.addPage();
      y = margin;
    }

    // Section title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(10, 37, 64);
    doc.text(section.title, margin, y);
    y += 6;

    // Rows
    for (let i = 0; i < section.rows.length; i++) {
      const row = section.rows[i];

      // Zebra stripe background
      if (i % 2 === 0) {
        doc.setFillColor(248, 250, 252); // slate-50
        doc.rect(margin, y - 4, contentWidth, 7, 'F');
      }

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(71, 85, 105); // slate-600
      doc.text(row.label, margin + 2, y);

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(10, 37, 64);
      doc.text(row.value, pageWidth - margin - 2, y, { align: 'right' });

      y += 7;
    }

    y += 6;
  }

  // Footer
  const footerY = 285;
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.line(margin, footerY - 4, pageWidth - margin, footerY - 4);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(
    'Generated by CalcRun.com — Free financial calculators, no signup, no ads.',
    margin,
    footerY,
  );
  doc.text(
    'This is an estimate for informational purposes only. Not financial advice.',
    margin,
    footerY + 4,
  );

  // Download
  const filename = data.toolName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+$/, '');
  doc.save(`${filename}-results.pdf`);
}
