/**
 * Client-side PDF export for financial calculator results.
 * Uses html2canvas to capture the rendered results panel (charts, tables,
 * breakdowns) and jsPDF to compose a branded PDF with inputs + visual results.
 */

export interface PdfInput {
  label: string;
  value: string;
}

export interface PdfExportOptions {
  toolName: string;
  inputs: PdfInput[];
  resultsElement: HTMLElement;
}

export async function exportToPdf(options: PdfExportOptions): Promise<void> {
  const [{ jsPDF }, { default: html2canvas }] = await Promise.all([
    import('jspdf'),
    import('html2canvas'),
  ]);

  const { toolName, inputs, resultsElement } = options;

  // Hide elements marked with data-pdf-hide during capture
  const hiddenEls = resultsElement.querySelectorAll<HTMLElement>('[data-pdf-hide]');
  const prevDisplays: string[] = [];
  hiddenEls.forEach((el, i) => {
    prevDisplays[i] = el.style.display;
    el.style.display = 'none';
  });

  // Replace SVG charts with <img> elements before capture. html2canvas 1.x
  // cannot reliably render complex SVGs (gradients, transforms, recharts).
  // Using <img src="data:image/svg+xml..."> avoids both SVG rendering issues
  // AND canvas-taint issues (data URLs are same-origin, Blob URLs can taint).
  const svgReplacements: Array<{ svg: SVGSVGElement; img: HTMLImageElement }> = [];
  const svgEls = Array.from(resultsElement.querySelectorAll<SVGSVGElement>('svg'));

  for (const svg of svgEls) {
    const rect = svg.getBoundingClientRect();
    // Skip small SVGs (icons) — only rasterize chart-sized SVGs
    if (rect.width < 100 || rect.height < 50) continue;

    try {
      const clone = svg.cloneNode(true) as SVGSVGElement;
      if (!clone.getAttribute('xmlns')) {
        clone.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
      }
      clone.setAttribute('width', String(rect.width));
      clone.setAttribute('height', String(rect.height));

      // Inline computed font styles on text elements — external CSS is lost
      // when the SVG is loaded as a standalone image
      const origTexts = svg.querySelectorAll('text, tspan');
      const cloneTexts = clone.querySelectorAll('text, tspan');
      for (let i = 0; i < origTexts.length && i < cloneTexts.length; i++) {
        const cs = getComputedStyle(origTexts[i]);
        const t = cloneTexts[i] as SVGElement;
        t.setAttribute('font-family', cs.fontFamily);
        t.setAttribute('font-size', cs.fontSize);
        t.setAttribute('font-weight', cs.fontWeight);
      }

      const xml = new XMLSerializer().serializeToString(clone);
      const dataUrl = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(xml)}`;

      const img = document.createElement('img');
      img.style.width = `${rect.width}px`;
      img.style.height = `${rect.height}px`;

      await new Promise<void>((resolve, reject) => {
        img.onload = () => resolve();
        img.onerror = () => reject(new Error('SVG image load failed'));
        img.src = dataUrl;
      });

      if (svg.parentNode) {
        svg.parentNode.replaceChild(img, svg);
        svgReplacements.push({ svg, img });
      }
    } catch {
      // If rasterization fails for one SVG, skip it — html2canvas will try its best
    }
  }

  let canvas: HTMLCanvasElement;
  try {
    // Capture the results panel (charts, tables, big numbers — everything)
    canvas = await html2canvas(resultsElement, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#FAFAFA',
    });
  } finally {
    // Always restore hidden elements, even if html2canvas throws
    hiddenEls.forEach((el, i) => {
      el.style.display = prevDisplays[i];
    });
    // Restore original SVGs
    for (const { svg, img } of svgReplacements) {
      img.parentNode?.replaceChild(svg, img);
    }
  }

  // ── Build PDF ──────────────────────────────────────────
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const m = 15;
  const cw = pw - m * 2;
  const footerReserve = 16;

  function addFooter() {
    const fy = ph - 10;
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(m, fy - 3, pw - m, fy - 3);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by CalcRun.com — Free financial calculators.', m, fy);
    doc.text(
      'This is an estimate for informational purposes only. Not financial advice.',
      m,
      fy + 3,
    );
  }

  // ── Header ─────────────────────────────────────────────
  // Accent bar
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pw, 3, 'F');

  // Logo
  let y = 14;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(10, 37, 64);
  doc.text('Calc', m, y);
  const calcW = doc.getTextWidth('Calc');
  doc.setTextColor(37, 99, 235);
  doc.text('Run', m + calcW, y);

  // Date
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  doc.text(dateStr, pw - m, y, { align: 'right' });

  // Tool name
  y = 24;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(10, 37, 64);
  doc.text(toolName, m, y);

  // Divider
  y += 4;
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(m, y, pw - m, y);
  y += 7;

  // ── Your Inputs ────────────────────────────────────────
  if (inputs.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(10, 37, 64);
    doc.text('Your Inputs', m, y);
    y += 5;

    for (let i = 0; i < inputs.length; i++) {
      if (i % 2 === 0) {
        doc.setFillColor(248, 250, 252);
        doc.rect(m, y - 3.5, cw, 6, 'F');
      }

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text(inputs[i].label, m + 2, y);

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(10, 37, 64);
      doc.text(inputs[i].value, pw - m - 2, y, { align: 'right' });

      y += 6;
    }

    y += 4;
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(m, y, pw - m, y);
    y += 7;
  }

  // ── Results Screenshot ─────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(10, 37, 64);
  doc.text('Results', m, y);
  y += 4;

  const imgWidth = cw;
  const imgHeight = (canvas.height / canvas.width) * imgWidth;
  const pxPerMm = canvas.width / imgWidth;
  const maxContent = ph - footerReserve;

  let srcY = 0;
  let firstChunk = true;

  while (srcY < canvas.height) {
    const spaceOnPage = firstChunk ? maxContent - y : maxContent - m;
    const remainingMm = (canvas.height - srcY) / pxPerMm;
    const chunkMm = Math.min(spaceOnPage, remainingMm);
    const chunkPx = Math.round(chunkMm * pxPerMm);

    if (!firstChunk) {
      doc.addPage();
      y = m;
    }

    // Slice and render canvas chunk
    const chunk = document.createElement('canvas');
    chunk.width = canvas.width;
    chunk.height = chunkPx;
    const ctx = chunk.getContext('2d');
    if (ctx) {
      ctx.drawImage(canvas, 0, srcY, canvas.width, chunkPx, 0, 0, canvas.width, chunkPx);
      doc.addImage(chunk.toDataURL('image/png'), 'PNG', m, y, imgWidth, chunkMm);
    }

    srcY += chunkPx;
    firstChunk = false;

    addFooter();
  }

  // Edge case: if the results element was empty / zero height
  if (srcY === 0) {
    addFooter();
  }

  // ── Download ───────────────────────────────────────────
  const filename = toolName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+$/, '');
  doc.save(`${filename}-results.pdf`);
}
